name: Build SoltrOS Server ISO
on:
  workflow_dispatch:
  # You can also trigger on releases or tags
  # release:
  #   types: [published]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create kickstart configuration
        run: |
          mkdir -p kickstart
          cat > kickstart/soltros-server.ks << 'EOF'
          # Use text mode install
          text
          
          # Keyboard layouts
          keyboard --xlayouts='us'
          
          # System language
          lang en_US.UTF-8
          
          # Network information
          network --bootproto=dhcp --device=link --activate
          
          # Use network installation
          url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-42&arch=x86_64"
          
          # Root password (you should change this or use --iscrypted with a hashed password)
          rootpw --plaintext soltros123
          
          # System services
          services --enabled="NetworkManager,sshd"
          
          # System timezone
          timezone America/New_York --utc
          
          # User creation during installation
          user --groups=wheel --name=soltros --password=soltros123 --plaintext --gecos="SoltrOS User"
          
          # Disk partitioning
          autopart
          clearpart --none --initlabel
          
          # SELinux configuration
          selinux --enforcing
          
          # Firewall configuration
          firewall --enabled --ssh
          
          # Skip X config
          skipx
          
          # Package selection
          %packages
          @core
          @standard
          NetworkManager
          openssh-server
          sudo
          %end
          
          # Post-installation script
          %post --log=/var/log/anaconda/post-install.log
          # Enable sudo for wheel group
          echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers.d/wheel
          
          # Set up SSH keys if needed
          # mkdir -p /home/soltros/.ssh
          # echo "your-ssh-public-key-here" > /home/soltros/.ssh/authorized_keys
          # chown -R soltros:soltros /home/soltros/.ssh
          # chmod 700 /home/soltros/.ssh
          # chmod 600 /home/soltros/.ssh/authorized_keys
          
          # Additional post-installation customizations can go here
          %end
          
          # Reboot after installation
          reboot
          EOF
      
      - name: Generate ISO filename
        id: iso-name
        run: |
          echo "iso-name=soltros-server-$(date +%Y%m%d).iso" >> $GITHUB_OUTPUT
      
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: soltros-os-server
          image_repo: ghcr.io/${{ github.repository_owner }}
          image_tag: latest
          version: 42
          variant: Silverblue
          iso_name: ${{ steps.iso-name.outputs.iso-name }}
          enrollment_password: universalblue
          secure_boot_key_url: 'https://github.com/ublue-os/akmods/raw/main/certs/public_key.der'
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"
          kickstart_file: kickstart/soltros-server.ks
      
      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.iso-name.outputs.iso-name }}
          path: ${{ steps.build.outputs.iso_path }}
          retention-days: 30
      
      - name: Upload checksum as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.iso-name.outputs.iso-name }}-checksum
          path: ${{ steps.build.outputs.iso_path }}.sha256
          retention-days: 30
